# Generated by Django 5.2.7 on 2025-10-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_warehouse', '0002_borrower_book_borrowed_at_book_borrowed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
